version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: product-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

  product-api:
    build: .
    container_name: product-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Spring Boot leerá estas variables
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/product_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  product_data:
