version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: product-db
    environment:
      # Estas variables de entorno se asignarán al contenedor de PostgreSQL
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: productdb
    ports:
      - "5432:5432"
    volumes:
      - product_data:/var/lib/postgresql/data

  product-api:
    build: .
    container_name: product-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Spring Boot leerá estas variables
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  product_data:
